server:
  port: 8003

spring:
  application:
    name: MESSAGE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/message
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#services:
#  customer:
#    url: http://CUSTOMER-SERVICE:8001/api/v2/customer



#credentialRequest:
#  username: "RemitTest"
#  password: "Remit@Test123"
#  applicationName: "RemitTest"
#  creationDate: "2024-04-04T00:00:00Z"
#  organizationCode: "RemitTest"
#  email: "TEST@1234"
#
#
#httpHeaders:
#  organisationCode: "RemitTest"
#  contentType: "application/json"
#  basicAuth:
#    username: "RemitTest"
#    password: "Remit@Test123"
